services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: rabbitmqHost
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '15674:15674'
      - '15672'
      - '5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
